# Generated by Django 5.0.4 on 2024-04-08 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_id_number'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Product',
        ),
    ]
